export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILURE = "VERIFY_FAILURE";
export const RESEND_OTP_REQUEST = "RESEND_OTP_REQUEST";
export const RESEND_OTP_SUCCESS = "RESEND_OTP_SUCCESS";
export const RESEND_OTP_FAILURE = "RESEND_OTP_FAILURE";

export const SASS_LOGIN_REQUEST = "SASS_LOGIN_REQUEST";
export const SASS_LOGIN_SUCCESS = "SASS_LOGIN_SUCCESS";
export const SASS_LOGIN_FAILURE = "SASS_LOGIN_FAILURE";

export const GLOBAL_DATA_REQUEST = "GLOBAL_DATA_REQUEST";
export const GLOBAL_DATA_SUCCESS = "GLOBAL_DATA_SUCCESS";
export const GLOBAL_DATA_FAILURE = "GLOBAL_DATA_FAILURE";

export const LOGOUT = "LOGOUT";

export const ALL_ORGANIZATION_REQUEST = "ALL_ORGANIZATION_REQUEST";
export const ALL_ORGANIZATION_SUCCESS = "ALL_ORGANIZATION_SUCCESS";
export const ALL_ORGANIZATION_FAILURE = "ALL_ORGANIZATION_FAILURE";

export const SALES_ORDER_REQUEST = "SALES_ORDER_REQUEST";
export const SALES_ORDER_SUCCESS = "SALES_ORDER_SUCCESS";
export const SALES_ORDER_FAILURE = "SALES_ORDER_FAILURE";

export const SALES_ORDER_DETAILS_REQUEST = "SALES_ORDER_DETAILS_REQUEST";
export const SALES_ORDER_DETAILS_SUCCESS = "SALES_ORDER_DETAILS_SUCCESS";
export const SALES_ORDER_DETAILS_FAILURE = "SALES_ORDER_DETAILS_FAILURE";

export const SEARCH_CUSTOMER_REQUEST = "SEARCH_CUSTOMER_REQUEST";
export const SEARCH_CUSTOMER_SUCCESS = "SEARCH_CUSTOMER_SUCCESS";
export const SEARCH_CUSTOMER_FAILURE = "SEARCH_CUSTOMER_FAILURE";

export const CATEGORY_SEARCH_REQUEST = "CATEGORY_SEARCH_REQUEST";
export const CATEGORY_SEARCH_SUCCESS = "CATEGORY_SEARCH_SUCCESS";
export const CATEGORY_SEARCH_FAILURE = "CATEGORY_SEARCH_FAILURE";

export const BRAND_SEARCH_REQUEST = "BRAND_SEARCH_REQUEST";
export const BRAND_SEARCH_SUCCESS = "BRAND_SEARCH_SUCCESS";
export const BRAND_SEARCH_FAILURE = "BRAND_SEARCH_FAILURE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_FROM_QUOTE = "ADD_TO_CART_FROM_QUOTE";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";

export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";


export const TOTAL_AMOUNT = "TOTAL_AMOUNT";

export const CART_LINE_NAME_CHANGE = "CART_LINE_NAME_CHANGE";

export const SALES_ORDER_SUBMIT_REQUEST = "SALES_ORDER_SUBMIT_REQUEST";
export const SALES_ORDER_SUBMIT_SUCCESS = "SALES_ORDER_SUBMIT_SUCCESS";
export const SALES_ORDER_SUBMIT_FAILURE = "SALES_ORDER_SUBMIT_FAILURE";

export const GET_BILLTO_ADDRESS_REQUEST = "GET_BILLTO_ADDRESS_REQUEST";
export const GET_BILLTO_ADDRESS_SUCCESS = "GET_BILLTO_ADDRESS_SUCCESS";
export const GET_BILLTO_ADDRESS_FAILURE = "GET_BILLTO_ADDRESS_FAILURE";

export const GET_SHIPTO_ADDRESS_REQUEST = "GET_SHIPTO_ADDRESS_REQUEST";
export const GET_SHIPTO_ADDRESS_SUCCESS = "GET_SHIPTO_ADDRESS_SUCCESS";
export const GET_SHIPTO_ADDRESS_FAILURE = "GET_SHIPTO_ADDRESS_FAILURE";

export const WORK_ORDER_REQUEST = "WORK_ORDER_REQUEST";
export const WORK_ORDER_SUCCESS = "WORK_ORDER_SUCCESS";
export const WORK_ORDER_FAILURE = "WORK_ORDER_FAILURE";

export const WORK_ORDER_DETAILS_REQUEST = "WORK_ORDER_DETAILS_REQUEST";
export const WORK_ORDER_DETAILS_SUCCESS = "WORK_ORDER_DETAILS_SUCCESS";
export const WORK_ORDER_DETAILS_FAILURE = "WORK_ORDER_DETAILS_FAILURE";

export const WORK_ORDER_SEARCH_REQUEST = "WORK_ORDER_SEARCH_REQUEST";
export const WORK_ORDER_SEARCH_SUCCESS = "WORK_ORDER_SEARCH_SUCCESS";
export const WORK_ORDER_SEARCH_FAILURE = "WORK_ORDER_SEARCH_FAILURE";

export const RESOURCE_UPDATE_REQUEST = "RESOURCE_UPDATE_REQUEST";
export const RESOURCE_UPDATE_SUCCESS = "RESOURCE_UPDATE_SUCCESS";
export const RESOURCE_UPDATE_FAILURE = "RESOURCE_UPDATE_FAILURE";

export const CUSTOMER_SITES_REQUEST = "CUSTOMER_SITES_REQUEST";
export const CUSTOMER_SITES_SUCCESS = "CUSTOMER_SITES_SUCCESS";
export const CUSTOMER_SITES_FAILURE = "CUSTOMER_SITES_FAILURE";

export const CUSTOMER_CONTACTS_REQUEST = "CUSTOMER_CONTACTS_REQUEST";
export const CUSTOMER_CONTACTS_SUCCESS = "CUSTOMER_CONTACTS_SUCCESS";
export const CUSTOMER_CONTACTS_FAILURE = "CUSTOMER_CONTACTS_FAILURE";

export const SALES_QUOTE_SUBMIT_REQUEST = "SALES_QUOTE_SUBMIT_REQUEST";
export const SALES_QUOTE_SUBMIT_SUCCESS = "SALES_QUOTE_SUBMIT_SUCCESS";
export const SALES_QUOTE_SUBMIT_FAILURE = "SALES_QUOTE_SUBMIT_FAILURE";

export const SALES_QUOTE_REQUEST = "SALES_QUOTE_REQUEST";
export const SALES_QUOTE_SUCCESS = "SALES_QUOTE_SUCCESS";
export const SALES_QUOTE_FAILURE = "SALES_QUOTE_FAILURE";

export const SALES_QUOTE_DETAILS_REQUEST = "SALES_QUOTE_DETAILS_REQUEST";
export const SALES_QUOTE_DETAILS_SUCCESS = "SALES_QUOTE_DETAILS_SUCCESS";
export const SALES_QUOTE_DETAILS_FAILURE = "SALES_QUOTE_DETAILS_FAILURE";

export const SEARCH_LEAD_COMPANY_REQUEST = "SEARCH_LEAD_COMPANY_REQUEST";
export const SEARCH_LEAD_COMPANY_SUCCESS = "SEARCH_LEAD_COMPANY_SUCCESS";
export const SEARCH_LEAD_COMPANY_FAILURE = "SEARCH_LEAD_COMPANY_FAILURE";

export const SEARCH_LEAD_REQUEST = "SEARCH_LEAD_REQUEST";
export const SEARCH_LEAD_SUCCESS = "SEARCH_LEAD_SUCCESS";
export const SEARCH_LEAD_FAILURE = "SEARCH_LEAD_FAILURE";

export const LEAD_DETAILS_REQUEST = "LEAD_DETAILS_REQUEST";
export const LEAD_DETAILS_SUCCESS = "LEAD_DETAILS_SUCCESS";
export const LEAD_DETAILS_FAILURE = "LEAD_DETAILS_FAILURE";

export const LEAD_SUBMIT_REQUEST = "LEAD_SUBMIT_REQUEST";
export const LEAD_SUBMIT_SUCCESS = "LEAD_SUBMIT_SUCCESS";
export const LEAD_SUBMIT_FAILURE = "LEAD_SUBMIT_FAILURE";

export const LEAD_ACTIVITIES_REQUEST = "LEAD_ACTIVITIES_REQUEST";
export const LEAD_ACTIVITIES_SUCCESS = "LEAD_ACTIVITIES_SUCCESS";
export const LEAD_ACTIVITIES_FAILURE = "LEAD_ACTIVITIES_FAILURE";

export const LEAD_ACTIVITIES_CREATE_REQUEST = "LEAD_ACTIVITIES_CREATE_REQUEST";
export const LEAD_ACTIVITIES_CREATE_SUCCESS = "LEAD_ACTIVITIES_CREATE_SUCCESS";
export const LEAD_ACTIVITIES_CREATE_FAILURE = "LEAD_ACTIVITIES_CREATE_FAILURE";

export const LEAD_ACTIVITY_TYPE_REQUEST = "LEAD_ACTIVITY_TYPE_REQUEST";
export const LEAD_ACTIVITY_TYPE_SUCCESS = "LEAD_ACTIVITY_TYPE_SUCCESS";
export const LEAD_ACTIVITY_TYPE_FAILURE = "LEAD_ACTIVITY_TYPE_FAILURE";

export const RESOURCE_TRANSACTIONS_SEARCH_REQUEST = "RESOURCE_TRANSACTIONS_SEARCH_REQUEST";
export const RESOURCE_TRANSACTIONS_SEARCH_SUCCESS = "RESOURCE_TRANSACTIONS_SEARCH_SUCCESS";
export const RESOURCE_TRANSACTIONS_SEARCH_FAILURE = "RESOURCE_TRANSACTIONS_SEARCH_FAILURE";

export const RESOURCE_TRANSACTIONS_DETAILS_REQUEST = "RESOURCE_TRANSACTIONS_DETAILS_REQUEST";
export const RESOURCE_TRANSACTIONS_DETAILS_SUCCESS = "RESOURCE_TRANSACTIONS_DETAILS_SUCCESS";
export const RESOURCE_TRANSACTIONS_DETAILS_FAILURE = "RESOURCE_TRANSACTIONS_DETAILS_FAILURE";

export const RESOURCE_WORK_ORDER_SEARCH_REQUEST = "RESOURCE_WORK_ORDER_SEARCH_REQUEST";
export const RESOURCE_WORK_ORDER_SEARCH_SUCCESS = "RESOURCE_WORK_ORDER_SEARCH_SUCCESS";
export const RESOURCE_WORK_ORDER_SEARCH_FAILURE = "RESOURCE_WORK_ORDER_SEARCH_FAILURE";

export const SELECTED_RESOURCE_WORK_ORDER_SEARCH_REQUEST = "SELECTED_RESOURCE_WORK_ORDER_SEARCH_REQUEST";
export const SELECTED_RESOURCE_WORK_ORDER_SEARCH_SUCCESS = "SELECTED_RESOURCE_WORK_ORDER_SEARCH_SUCCESS";
export const SELECTED_RESOURCE_WORK_ORDER_SEARCH_FAILURE = "SELECTED_RESOURCE_WORK_ORDER_SEARCH_FAILURE";

export const RESOURCE_CODE_SEARCH_REQUEST = "RESOURCE_CODE_SEARCH_REQUEST";
export const RESOURCE_CODE_SEARCH_SUCCESS = "RESOURCE_CODE_SEARCH_SUCCESS";
export const RESOURCE_CODE_SEARCH_FAILURE = "RESOURCE_CODE_SEARCH_FAILURE";

export const SELECTED_RESOURCE_CODE_SEARCH_REQUEST = "SELECTED_RESOURCE_CODE_SEARCH_REQUEST";
export const SELECTED_RESOURCE_CODE_SEARCH_SUCCESS = "SELECTED_RESOURCE_CODE_SEARCH_SUCCESS";
export const SELECTED_RESOURCE_CODE_SEARCH_FAILURE = "SELECTED_RESOURCE_CODE_SEARCH_FAILURE";

export const RESOURCE_SUBMIT_REQUEST = "RESOURCE_SUBMIT_REQUEST";
export const RESOURCE_SUBMIT_SUCCESS = "RESOURCE_SUBMIT_SUCCESS";
export const RESOURCE_SUBMIT_FAILURE = "RESOURCE_SUBMIT_FAILURE";

export const WORK_ORDER_FIND_START = "WORK_ORDER_FIND_START";
export const WORK_ORDER_FIND_SUCCESS = "WORK_ORDER_FIND_SUCCESS";
export const WORK_ORDER_FIND_FAILURE = "WORK_ORDER_FIND_FAILURE";

//...WO_DETAILS...//
export const WO_DETAILS_REQUEST = "WO_DETAILS_REQUEST";
export const WO_DETAILS_SUCCESS = "WO_DETAILS_SUCCESS";
export const WO_DETAILS_FAILURE = "WO_DETAILS_FAILURE";
//export const SALES_MODULE_ACCESS = "SALES_MODULE_ACCESS";

export const SALESQUOTE_CUSTOMER_REQUEST = "SALESQUOTE_CUSTOMER_REQUEST";
export const SALESQUOTE_CUSTOMER_SUCCESS = "SALESQUOTE_CUSTOMER_SUCCESS";
export const SALESQUOTE_CUSTOMER_FAILURE = "SALESQUOTE_CUSTOMER_FAILURE";

// For Sales Order

export const SALES_ORDER_ADD_TO_CART = "SALES_ORDER_ADD_TO_CART";
export const SALES_ORDER_REMOVE_FROM_CART = "SALES_ORDER_REMOVE_FROM_CART";
export const SALES_ORDER_INCREMENT = "SALES_ORDER_INCREMENT";
export const SALES_ORDER_DECREMENT = "SALES_ORDER_DECREMENT";
export const SALES_ORDER_CART_LINE_NAME_CHANGE = "SALES_ORDER_CART_LINE_NAME_CHANGE";
export const SALES_ORDER_ADD_TO_CART_START = "SALES_ORDER_ADD_TO_CART_START"
export const SALES_ORDER_ADD_TO_CART_SUCCESS = "SALES_ORDER_ADD_TO_CART_SUCCESS"
export const SALES_ORDER_ADD_TO_CART_FAILURE = "SALES_ORDER_ADD_TO_CART_FAILURE"
export const SALES_ORDER_TOTAL_AMOUNT = "SALES_ORDER_TOTAL_AMOUNT";

// For Sales Order
export const GET_CUST_OUTSTANDING_REQUEST = "GET_CUST_OUTSTANDING_REQUEST";
export const GET_CUST_OUTSTANDING_SUCCESS = "GET_CUST_OUTSTANDING_SUCCESS";
export const GET_CUST_OUTSTANDING_FAILURE = "GET_CUST_OUTSTANDING_FAILURE";

export const GET_CUST_PENDING_INVOICES_REQUEST = "GET_CUST_PENDING_INVOICES_REQUEST";
export const GET_CUST_PENDING_INVOICES_SUCCESS = "GET_CUST_PENDING_INVOICES_SUCCESS";
export const GET_CUST_PENDING_INVOICES_FAILURE = "GET_CUST_PENDING_INVOICES_FAILURE";

// FOR SALES QUOTE MODULE
export const SQ_TERMS_TEMPLATE_REQUEST = "SQ_TERMS_TEMPLATE_REQUEST";
export const SQ_TERMS_TEMPLATE_SUCCESS = "SQ_TERMS_TEMPLATE_SUCCESS";
export const SQ_TERMS_TEMPLATE_FAILURE = "SQ_TERMS_TEMPLATE_FAILURE";

// DELIVERY
export const DELIVERY_REQUEST_START = "DELIVERY_REQUEST_START";
export const DELIVERY_REQUEST_SUCCESS = "DELIVERY_REQUEST_SUCCESS";
export const DELIVERY_REQUEST_FAILURE = "DELIVERY_REQUEST_FAILURE";

export const DELIVERY_CONFIRM_REQUEST_START = "DELIVERY_CONFIRM_REQUEST_START";
export const DELIVERY_CONFIRM_REQUEST_SUCCESS = "DELIVERY_CONFIRM_REQUEST_SUCCESS";
export const DELIVERY_CONFIRM_REQUEST_FAILURE = "DELIVERY_CONFIRM_REQUEST_FAILURE";